portal/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from portal.academy.views import HomeRedirectView
from portal.users.views import InstructorsSignupView

urlpatterns = [
    # General
    path("accounts/", include("allauth.urls")),
    path(
        "accounts/instructor/signup/",
        InstructorsSignupView.as_view(),
        name="instructors_signup",
    ),
    path("", HomeRedirectView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        "users/",
        include("portal.users.urls", namespace="users"),
    ),
    # Admissions
    path("admissions/", include("portal.admissions.urls")),
    # Academy
    path("academy/", include("portal.academy.urls")),
    path("hackathons/", include("portal.hackathons.urls")),
    path("capstone/", include("portal.capstone.urls")),
    # Grading
    path("grading/", include("portal.grading.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]

portal/portal/academy/urls.py
from django.urls import path

from . import views

app_name = "academy"

urlpatterns = [
    # Student Views
    path(
        r"student/units/",
        view=views.StudentUnitListView.as_view(),
        name="student-unit-list",
    ),
    path(
        r"student/units/<str:pk>/",
        view=views.StudentUnitDetailView.as_view(),
        name="student-unit-detail",
    ),
    # Instructor Views
    path(
        r"instructor/students/",
        view=views.InstructorUserListView.as_view(),
        name="instructor-user-list",
    ),
    path(
        r"instructor/students/<str:download>/",
        view=views.InstructorUserListView.as_view(),
        name="instructor-user-list-export",
    ),
    path(
        r"instructor/units/",
        view=views.InstructorUnitListView.as_view(),
        name="instructor-unit-list",
    ),
    path(
        r"instructor/units/<str:pk>/",
        view=views.InstructorUnitDetailView.as_view(),
        name="instructor-unit-detail",
    ),
]

portal/portal/staff/urls.py
from django.urls import path

from portal.staff import views

app_name = "staff"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("events", views.EventsView.as_view(), name="events"),
    path("candidates", views.CandidateListView.as_view(), name="candidate-list"),
    path(
        "candidates/<slug:pk>/",
        views.CandidateDetailView.as_view(),
        name="candidate-detail",
    ),
    path(
        "applications",
        views.ApplicationView.as_view(),
        name="application-list",
    ),
    path("submissions", views.SubmissionView.as_view(), name="submission-list"),
    path(
        "submissions/download/<int:pk>",
        views.SubmissionDownloadView.as_view(),
        name="submission-download",
    ),
    path(
        "submissions/download-feedback/<int:pk>",
        views.SubmissionFeedbackDownloadView.as_view(),
        name="submission-feedback-download",
    ),
    path("selections/", views.SelectionListView.as_view(), name="selection-list"),
    path(
        "selections/draw",
        views.SelectionDrawView.as_view(),
        name="selection-draw",
    ),
    path(
        "selections/reject-draw/<int:candidate_id>",
        views.SelectionRejectView.as_view(),
        name="selection-reject",
    ),
    path(
        "selections/select",
        views.SelectionSelectView.as_view(),
        name="selection-select",
    ),
    path("interviews", views.InterviewListView.as_view(), name="interview-list"),
    path(
        "interviews/<int:pk>",
        views.InterviewDetailView.as_view(),
        name="interview-detail",
    ),
    path("payments", views.PaymentListView.as_view(), name="payment-list"),
    path(
        "payments/<int:pk>",
        views.PaymentDetailView.as_view(),
        name="payment-detail",
    ),
    path(
        "payments/<int:pk>/reset",
        views.PaymentResetView.as_view(),
        name="payment-reset",
    ),
    path("exports", views.ExportView.as_view(), name="export"),
    path(
        "export-candidates",
        views.ExportCandidatesView.as_view(),
        name="export-candidates",
    ),
]

portal/portal/users/urls.py
from django.urls import path

from portal.users.views import (
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("profile/", view=user_update_view, name="profile"),
]

portal/portal/selection/models.py
import uuid
from pathlib import Path

from django.db import models

from .status import SelectionStatus


class Selection(models.Model):
    user = models.OneToOneField("users.User", on_delete=models.CASCADE, editable=False)

    status = models.CharField(
        default=SelectionStatus.PASSED_TEST, null=False, max_length=40
    )

    draw_rank = models.IntegerField(null=True, default=None)

    payment_value = models.FloatField(null=True, blank=True, default=None)
    ticket_type = models.CharField(null=True, blank=True, default=None, max_length=40)
    payment_due_date = models.DateTimeField(null=True, blank=True, default=None)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


doc_type_choices = [
    ("payment_proof", "Payment Proof"),
    ("student_id", "Student ID"),
]


def get_path(instance, filename):
    path = Path(filename)
    key_basename = path.parent / path.stem
    key_ext = path.suffix
    filename = f"{key_basename}_{uuid.uuid4().hex}{key_ext}"
    return f"payments/{instance.doc_type}/{instance.selection.user.username}/{filename}"


class SelectionDocument(models.Model):
    selection = models.ForeignKey(
        "selection.Selection",
        on_delete=models.CASCADE,
        related_name="documents",
    )
    doc = models.FileField(upload_to=get_path, null=True, blank=True)
    doc_type = models.CharField(
        blank=False, null=False, max_length=20, choices=doc_type_choices
    )

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


class SelectionLogs(models.Model):
    selection = models.ForeignKey(
        "selection.Selection",
        on_delete=models.CASCADE,
        related_name="logs",
        editable=False,
    )

    event = models.CharField(null=False, max_length=40, editable=False)
    message = models.TextField(null=False, editable=False)

    created_at = models.DateTimeField(auto_now_add=True)

portal/portal/users/models.py
from cryptography.hazmat.backends import (
    default_backend as crypto_default_backend,
)
from cryptography.hazmat.primitives import (
    serialization as crypto_serialization,
)
from cryptography.hazmat.primitives.asymmetric import rsa
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class UserWhitelist(models.Model):
    username = models.CharField(_("Username"), max_length=255, unique=True)
    is_student = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.username}"


class Gender(models.TextChoices):
    female = "female", _("Female")
    male = "male", _("Male")
    other = "other", _("Other/Prefer not to say")


class TicketTypeSelectable(models.TextChoices):
    student = "student", _("Student")
    regular = "regular", _("Regular")
    company = "company", _("Company")


class TicketType(models.TextChoices):
    student = "student", _("Student")
    regular = "regular", _("Regular")
    company = "company", _("Company")
    scholarship = "scholarship", _("Scholarship")


# Preference for in-person or remote
class AcademyTypePreference(models.TextChoices):
    in_person_then_remote = "in_person_then_remote", _("In-person then remote")
    remote_then_in_person = "remote_then_in_person", _("Remote then in-person")
    remote_only = "remote_only", _("Remote only")
    in_person_only = "in_person_only", _("In-person only")


# TODO: custom user manager to filter out users with unverified email addresses
class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    # Academy
    is_student = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)
    slack_member_id = models.TextField(blank=True)
    github_username = models.TextField(blank=True)
    deploy_private_key = models.TextField(blank=True)
    deploy_public_key = models.TextField(blank=True)

    # Admissions
    code_of_conduct_accepted = models.BooleanField(default=False)
    applying_for_scholarship = models.BooleanField(default=None, null=True)
    academy_type_preference = models.CharField(
        blank=True,
        null=True,
        max_length=50,
        choices=AcademyTypePreference.choices,
    )
    profession = models.CharField(blank=True, max_length=50)
    gender = models.CharField(null=False, max_length=25, choices=Gender.choices)
    ticket_type = models.CharField(
        null=False, max_length=25, choices=TicketType.choices
    )
    company = models.CharField(blank=True, max_length=100)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # Academy graduation eligibility fields
    can_graduate = models.BooleanField(default=True)
    can_attend_next = models.BooleanField(default=True)

    failed_or_dropped = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def save(self, *args, **kwargs):
        if not self.deploy_private_key and not self.deploy_public_key:
            key = rsa.generate_private_key(
                backend=crypto_default_backend(),
                public_exponent=65537,
                key_size=2048,
            )
            self.deploy_private_key = key.private_bytes(
                crypto_serialization.Encoding.PEM,
                crypto_serialization.PrivateFormat.PKCS8,
                crypto_serialization.NoEncryption(),
            ).decode("utf8")

            self.deploy_public_key = (
                key.public_key()
                .public_bytes(
                    crypto_serialization.Encoding.OpenSSH,
                    crypto_serialization.PublicFormat.OpenSSH,
                )
                .decode("utf8")
            )

        super().save(*args, **kwargs)

portal/portal/capstone/forms.py
from django import forms

from portal.capstone import models


class ApiForm(forms.ModelForm):
    class Meta:
        model = models.StudentApi
        fields = ["url"]


class ReportForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = ["file"]

portal/portal/capstone/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from rest_framework.response import Response
from rest_framework.views import APIView

from portal.capstone import forms, models
from portal.users.models import User
from portal.users.views import InstructorMixin, StudentMixin

logger = logging.getLogger(__name__)


class StudentCapstoneListView(StudentMixin, ListView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/student/capstone_list.html"

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        self.object_list = self.get_queryset()
        data = []
        for capstone in self.object_list:
            api, _ = models.StudentApi.objects.get_or_create(
                capstone=capstone, user=request.user
            )
            data.append((capstone, api))

        context = self.get_context_data(object_list=data)
        return self.render_to_response(context)


class StudentCapstoneDetailView(StudentMixin, DetailView):
    model = models.Capstone
    template_name = "capstone/student/capstone_detail.html"

    # noinspection PyAttributeOutsideInit
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset=queryset)

        api, _ = models.StudentApi.objects.get_or_create(
            capstone=self.object,
            user=self.request.user,
        )

        reports = {}
        for type_choice in models.Report.Type.choices:
            report, _ = models.Report.objects.get_or_create(
                capstone=self.object,
                user=self.request.user,
                type=type_choice[0],
            )
            reports[type_choice[0]] = report

        return self.object, api, reports

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        capstone, api, reports = self.get_object()
        context = self.get_context_data(
            capstone=capstone,
            api=api,
            api_form=forms.ApiForm(instance=api),
            reports=[
                [report_type, forms.ReportForm(instance=report), report]
                for report_type, report in reports.items()
                if getattr(capstone, f"{report_type}_open")
            ],
        )
        return self.render_to_response(context)

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        capstone, api, reports = self.get_object()

        if "submit_api" in request.POST:
            form = forms.ApiForm(request.POST, instance=api)
            if form.is_valid():
                form.save()

        else:
            for report_type, report in reports.items():
                if f"submit_{report_type}" in request.POST:
                    form = forms.ReportForm(
                        request.POST, request.FILES, instance=report
                    )
                    if form.is_valid():
                        form.save()
                        messages.add_message(
                            request,
                            messages.SUCCESS,
                            "Report submited successfully!",
                        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("capstone:student-capstone-detail", args=(self.object.pk,))


class InstructorCapstoneListView(InstructorMixin, ListView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/instructor/capstone_list.html"


class InstructorCapstoneDetailView(InstructorMixin, DetailView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/instructor/capstone_detail.html"

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        self.object = self.get_object()
        student_data = []
        for student in User.objects.filter(is_student=True):
            student_data.append(
                {
                    "user": student,
                    "api": models.StudentApi.objects.filter(
                        capstone=self.object,
                        user=student,
                    ).first(),
                    "proposal": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.proposal,
                    ).first(),
                    "report_provisory": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.report_provisory,
                    ).first(),
                    "report_final": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.report_final,
                    ).first(),
                },
            )

        context = self.get_context_data(
            object=self.object,
            students=student_data,
            workspace_url=settings.SLACK_WORKSPACE,
        )
        return self.render_to_response(context)


class CapstonePredictView(APIView):
    permission_classes = []

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        return Response({"proba": 0.6})


class CapstoneUpdateView(APIView):
    permission_classes = []

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        return Response({"msg": "ok"})

portal/portal/templates/candidate_templates/academy_type.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="py-5">Select Your Preferred Academy Attendance Type</h2>
    <p>
        Both in-person and remote academy modes will have the same content and schedule.
        The only difference is that <br> the in-person academy will have the hackathons in-person. Hackathons last a full day and are scheduled for Sundays.<br>
        We will try to accommodate to your preference, but we cannot guarantee it as there are limited spots for each type of academy.
    </p>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="academy_type">Please choose your preferred academy type:</label>
                    <select class="form-control" id="academy_type" name="academy_type">
                        <option value="in_person_then_remote">Prefer in-person but can also do remote</option>
                        <option value="remote_then_in_person">Prefer remote but can also do in-person</option>
                        <option value="remote_only">Remote only</option>
                        <option value="in_person_only">In-person only</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

portal/portal/templates/candidate_templates/before_coding_test.html
{% extends 'base.html' %}
{% load tz %}

{% block content %}
{% timezone "Europe/Lisbon" %}

<div class="container">
    <h2 class="py-5">Coding Test</h2>

    <div class="jumbotron py-5">
        <h1 style="color:red;">Attention!</h1>

        <h2>You're about to start the coding test.</h2>
        <p>Once you start it, you'll only have <b>{{ ADMISSIONS_CODING_TEST_DURATION }} hours</b> to complete it.<br>
            You can make as many submissions as you want, and you only need 1 passing submission (at least <b>{{ coding_test_subtype.pass_score|floatformat }}</b> out of <b>{{ coding_test_subtype.max_score|floatformat }}</b> points).
        </p>
        <p>We'll only consider your <b>best</b> submission, not your last one.</p>
        <p>Please submit your test in any case, even if you think that you did not pass.</p>
        <p>Do not use vscode for solving the test, it might make the grading fail.</p>
        <p><h4>
            Please complete the setup before starting the coding test, 
            or you'll be wasting your precious test time setting up your environment!!!
        </h4></p>
        <p>
           Make sure you're free for the next {{ ADMISSIONS_CODING_TEST_DURATION }} hours before proceeding!
        </p>
            
        <form method="post" class="pt-4">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Understood & I'm ready!</button>
        </form>
    </div>

</div>

{% endtimezone %}
{% endblock %}

portal/portal/templates/candidate_templates/coding_test.html
{% extends 'base.html' %}
{% load tz %}

{% block content %}
{% timezone "Europe/Lisbon" %}


<div class="container">

    <div class="row">
        <div class="col-md-12 text-center">
            {% if status == "passed" %}
            <div class="alert alert-success" role="alert">
                You have passed with {{ best_score }}/{{ challenge.max_score }}!
            </div>
            {% endif %}
            {% if status == "ongoing"%}
            <div class="alert alert-warning" role="alert" id="countdown"> </div>
            {% endif %}
            {% if status == "failed" %}
            <div class="alert alert-danger" role="alert">
                You have failed!
            </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 py-4">
            <p>
                <h1 style="color:blue;">Welcome to the Coding Test!</h1>
            </p>
            <h2>Follow these instructions:</h2>
            <ol>
                    <li>Download the coding test with the button below</li>
                    <li>Create a virtual environment</li>
                    <li>Install the requirements from requirement.txt - they are different than for the SLUs</li>
                    <li>Run the exercise notebook </li>
                    <li>Upload the exercise notebook for grading</li>
                    <li>Please submit your test in any case, even if you think that you did not pass.</li>
                    <li>Do not use vscode for solving the test, it might make the grading fail.</li>
            </ol>

            <br>

            <div class="row">
                <div class="col-md-12 text-center">
                    {% if status == "passed" %}
                    <div class="alert alert-success" role="alert">
                        You have passed with {{ best_score }}/{{ challenge.max_score }}!
                    </div>
                    {% endif %}
                    {% if status == "ongoing"%}
                    <div class="alert alert-warning" role="alert" id="countdown"> </div>
                    {% endif %}
                    {% if status == "failed" %}
                    <div class="alert alert-danger" role="alert">
                        You have failed!
                    </div>
                    {% endif %}
                </div>
            </div>

            <p>
                <h2 style="color:magenta">Submitting your work for grading</h2>
            </p>
            <p style="margin-left:25px;">
                Upload the <code>Exercise Notebook</code> in the submission box below.
            </p>
            <p style="margin-left:25px;">
                <strong>You should upload only the <code>Exercise Notebook</code> with your solutions directly</strong>, 
                you don't need to create a zip file or anything else!
            </p>
            <p style="margin-left:25px;">
                After submitting, you'll see the grade and whether you passed or not.
                You need a score of at least 16 (out of 20). <br>
                Click in "Open" in the Feedback column to see how much you scored in each question.
            </p>
            <p style="margin-left:25px; margin-right:10%;">
                You can (and should!) make as many submissions as you like during the test!
            </p>

            <p>
                <h3 style="color:green;">Good luck!</h3>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-deck">
                <div class="card">
                    <div class="card-body d-flex flex-column">
                        <p class="card-text">Use the button below to download the coding test:</p>
                        <a href="{% url 'admissions:candidate:assignment-download' 'coding_test' %}" class="btn btn-primary {% if not download_enabled %} disabled {% endif %} mt-auto align-self-start" role="button" aria-pressed="true" target="_blank">Download</a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body d-flex flex-column">
                        <p class="card-text">Use the buttons below to upload the coding test for grading. <br> To see your grade, wait a minute after submitting, then refresh the page.</p>
                    <form action="{% url 'admissions:candidate:submission-upload' 'coding_test' %}" enctype="multipart/form-data" method="POST" class="m-0 mt-auto">
                        {% csrf_token %}
                        <div class="custom-file mb-3">
                            <input type="file" class="custom-file-input" id="submissionFile" name="file" required>
                            <label class="custom-file-label" for="submissionFile">Choose file</label>
                        </div>
                        <script>
                            $('#submissionFile').on('change',function(e){
                                var fileName = e.target.files[0].name;
                                $(this).next('.custom-file-label').html(fileName);
                            })
                        </script>
                        <button class="btn btn-primary" type="submit" {% if not upload_enabled %} disabled {% endif %}>Submit Solution</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "./submissions_table.html" %}

</div>

<script>
    var testDurationHours = {{ coding_test_duration_hours }};
    var testStartedAt = {{ coding_test_started_at_ms }};
    var yourDateToGo = new Date(testStartedAt + testDurationHours * 60 * 60 * 1000);
    var timing = setInterval(
        function () {
            var currentDate = new Date().getTime();
            var timeLeft = yourDateToGo - currentDate;

            var hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));

            var minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
            if (minutes < 10) minutes= "0" + minutes;

            var seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);
            if (seconds < 10) seconds= "0" +seconds;

            var txtAll = `You have <b>${hours}h ${minutes}m ${seconds}s</b> to submit solutions!`;
            document.getElementById("countdown").innerHTML = txtAll;

            if (timeLeft <= 0) {
                clearInterval(timing);
                document.getElementById("countdown").innerHTML = "Time's up!";
            }
        }, 1000);
</script>

{% endtimezone %}
{% endblock %}

portal/portal/templates/candidate_templates/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2 class="py-5">Profile</h2>

    <div class="row">
        <div class="col-md-8 order-md-8 mb-6">

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_full_name">Full name</label>
                    <input type="text" class="form-control" name="full_name" maxlength="100" id="id_full_name" placeholder="John Doe" value="{{profile.full_name}}" required>
                </div>
                <div class="form-group">
                    <label for="id_profession">Profession</label>
                    <input type="text" class="form-control" name="profession" maxlength="50" id="id_profession" placeholder="Marine Biologist" value="{{profile.profession}}" required>
                </div>

                <div class="form-group">
                    <label for="id_gender">Gender</label>
                    <select class="form-control" name="gender" id="id_gender" required>
                        <option value="" {% if not profile.gender %}selected{% endif %}>---------</option>
                        <option value="{{profile_genders.female}}" {% if profile.gender == profile_genders.female %}selected{% endif %}>{{profile_genders.female}}</option>
                        <option value="{{profile_genders.male}}" {% if profile.gender == profile_genders.male %}selected{% endif %}>{{profile_genders.male}}</option>
                        <option value="{{profile_genders.other}}" {% if profile.gender == profile_genders.other %}selected{% endif %}>{{profile_genders.other}}</option>
                    </select>
                </div>

                {% if not applying_for_scholarship %}
                <div class="form-group">
                    <label for="id_ticket_type">Ticket type</label>
                    <p class="text-muted"><i>
                        If you chose a student ticket, you'll need to show us a valid student card at payment time.<br>
                        To issue an invoice to a company, you must select the company ticket.<br>
                        Find all the information about our fees <a href="https://ldssa.github.io/wiki/Applicants/Application-process/">here</a>.
                    </i></p>
                    <select class="form-control" name="ticket_type" id="id_ticket_type"required>
                        <option value="" {% if not profile.ticket_type %}selected{% endif %}>---------</option>
                        <option value="{{profile_ticket_types.student}}" {% if profile.ticket_type == profile_ticket_types.student %}selected{% endif %}>{{profile_ticket_types.student}}</option>
                        <option value="{{profile_ticket_types.regular}}" {% if profile.ticket_type == profile_ticket_types.regular %}selected{% endif %}>{{profile_ticket_types.regular}}</option>
                        <option value="{{profile_ticket_types.company}}" {% if profile.ticket_type == profile_ticket_types.company %}selected{% endif %}>{{profile_ticket_types.company}}</option>
                    </select>
                </div>
                {% endif %}

                <div class="form-group">
                    <label for="id_company">Company</label>
                    {% if not applying_for_scholarship %}
                    <p class="text-muted"><i>
                        Optional if you've not selected a company ticket.
                    </i></p>
                    {% else %}
                    <p class="text-muted"><i>
                        Optional
                    </i></p>
                    {% endif %}
                    <input type="text" class="form-control" name="company" maxlength="50" id="id_company" placeholder="LDSA" value="{{profile.company}}">
                </div>

                <button type="submit" class="btn btn-primary">{% if profile_exists %}Update profile{% else %}Create Profile{% endif %}</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}