portal/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from portal.academy.views import HomeRedirectView
from portal.users.views import InstructorsSignupView

urlpatterns = [
    # General
    path("accounts/", include("allauth.urls")),
    path(
        "accounts/instructor/signup/",
        InstructorsSignupView.as_view(),
        name="instructors_signup",
    ),
    path("", HomeRedirectView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        "users/",
        include("portal.users.urls", namespace="users"),
    ),
    # Admissions
    path("admissions/", include("portal.admissions.urls")),
    # Academy
    path("academy/", include("portal.academy.urls")),
    path("hackathons/", include("portal.hackathons.urls")),
    path("capstone/", include("portal.capstone.urls")),
    # Grading
    path("grading/", include("portal.grading.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]

portal/portal/academy/urls.py
from django.urls import path

from . import views

app_name = "academy"

urlpatterns = [
    # Student Views
    path(
        r"student/units/",
        view=views.StudentUnitListView.as_view(),
        name="student-unit-list",
    ),
    path(
        r"student/units/<str:pk>/",
        view=views.StudentUnitDetailView.as_view(),
        name="student-unit-detail",
    ),
    # Instructor Views
    path(
        r"instructor/students/",
        view=views.InstructorUserListView.as_view(),
        name="instructor-user-list",
    ),
    path(
        r"instructor/students/<str:download>/",
        view=views.InstructorUserListView.as_view(),
        name="instructor-user-list-export",
    ),
    path(
        r"instructor/units/",
        view=views.InstructorUnitListView.as_view(),
        name="instructor-unit-list",
    ),
    path(
        r"instructor/units/<str:pk>/",
        view=views.InstructorUnitDetailView.as_view(),
        name="instructor-unit-detail",
    ),
]

portal/portal/hackathons/urls.py
from django.urls import path

from . import views

app_name = "hackathons"

urlpatterns = [
    # Leaderboard
    path(
        r"student/hackathons/<str:pk>/leaderboard/",
        view=views.LeaderboardView.as_view(),
        name="leaderboard",
    ),
    # FrankenLeaderboard
    path(
        r"student/hackathons/frankenleaderboard/",
        view=views.FrankenLeaderboardView.as_view(),
        name="frankenleaderboard",
    ),
    # API
    # https://portal.lisbondatascience.org/hackathons/api/setup/{codename}/
    path(
        r"api/setup/<str:pk>/",
        view=views.HackathonSetupView.as_view(),
        name="hackathon-setup",
    ),
    # Student Views
    path(
        r"student/hackathons/",
        view=views.StudentHackathonListView.as_view(),
        name="student-hackathon-list",
    ),
    path(
        r"student/hackathons/<str:pk>/",
        view=views.StudentHackathonDetailView.as_view(),
        name="student-hackathon-detail",
    ),
    # Instructor Views
    path(
        r"instructor/hackathons/",
        view=views.InstructorHackathonListView.as_view(),
        name="instructor-hackathon-list",
    ),
    path(
        r"instructor/hackathons/<str:pk>/settings",
        view=views.InstructorHackathonSettingsView.as_view(),
        name="instructor-hackathon-settings",
    ),
    path(
        r"instructor/hackathons/<str:pk>/",
        view=views.InstructorHackathonDetailView.as_view(),
        name="instructor-hackathon-detail",
    ),
    path(
        r"instructor/hackathons/<str:pk>/admin/",
        view=views.InstructorHackathonAdminView.as_view(),
        name="instructor-hackathon-admin",
    ),
]

portal/portal/staff/urls.py
from django.urls import path

from portal.staff import views

app_name = "staff"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("events", views.EventsView.as_view(), name="events"),
    path("candidates", views.CandidateListView.as_view(), name="candidate-list"),
    path(
        "candidates/<slug:pk>/",
        views.CandidateDetailView.as_view(),
        name="candidate-detail",
    ),
    path(
        "applications",
        views.ApplicationView.as_view(),
        name="application-list",
    ),
    path("submissions", views.SubmissionView.as_view(), name="submission-list"),
    path(
        "submissions/download/<int:pk>",
        views.SubmissionDownloadView.as_view(),
        name="submission-download",
    ),
    path(
        "submissions/download-feedback/<int:pk>",
        views.SubmissionFeedbackDownloadView.as_view(),
        name="submission-feedback-download",
    ),
    path("selections/", views.SelectionListView.as_view(), name="selection-list"),
    path(
        "selections/draw",
        views.SelectionDrawView.as_view(),
        name="selection-draw",
    ),
    path(
        "selections/reject-draw/<int:candidate_id>",
        views.SelectionRejectView.as_view(),
        name="selection-reject",
    ),
    path(
        "selections/select",
        views.SelectionSelectView.as_view(),
        name="selection-select",
    ),
    path("interviews", views.InterviewListView.as_view(), name="interview-list"),
    path(
        "interviews/<int:pk>",
        views.InterviewDetailView.as_view(),
        name="interview-detail",
    ),
    path("payments", views.PaymentListView.as_view(), name="payment-list"),
    path(
        "payments/<int:pk>",
        views.PaymentDetailView.as_view(),
        name="payment-detail",
    ),
    path(
        "payments/<int:pk>/reset",
        views.PaymentResetView.as_view(),
        name="payment-reset",
    ),
    path("exports", views.ExportView.as_view(), name="export"),
    path(
        "export-candidates",
        views.ExportCandidatesView.as_view(),
        name="export-candidates",
    ),
]

portal/portal/users/urls.py
from django.urls import path

from portal.users.views import (
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("profile/", view=user_update_view, name="profile"),
]

portal/portal/academy/models.py
#from datetime import datetime

from django.conf import settings
from django.db import models
from django.utils import timezone

LISBON_TZ = timezone.utc


class Specialization(models.Model):
    code = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.code


class Unit(models.Model):
    specialization = models.ForeignKey(
        Specialization,
        on_delete=models.CASCADE,
        related_name="units",
    )

    code = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    instructor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    due_date = models.DateField(default=timezone.now())
    open = models.BooleanField(default=False)

    checksum = models.TextField(blank=True)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.specialization.code}/{self.code}"


def notebook_path(instance, filename):
    now = timezone.now().astimezone().isoformat(timespec="seconds")
    return f"{instance.unit.code}/{instance.user.username}/notebook_{now}.ipynb"


def feedback_path(instance, filename):
    now = timezone.now().isoformat(timespec="seconds")
    return f"{instance.unit.code}/{instance.user.username}/feedback_{now}.ipynb"


class Grade(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="grades",
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name="grades")
    created = models.DateTimeField(auto_now_add=True)
    notebook = models.FileField(upload_to=notebook_path, null=True, blank=True)

    STATUSES = (
        ("never-submitted", "Unsubmitted"),
        ("sent", "Sent"),
        ("grading", "Grading"),
        ("failed", "Grading failed"),
        ("out-of-date", "Out-of-date"),
        ("checksum-failed", "Checksum verification failed"),
        ("graded", "Graded"),
    )
    status = models.CharField(
        max_length=1024, choices=STATUSES, default="never-submitted"
    )
    score = models.FloatField(null=True, blank=True)
    message = models.TextField(blank=True)
    feedback = models.FileField(upload_to=feedback_path, null=True)
    on_time = models.BooleanField(default=True)

portal/portal/capstone/forms.py
from django import forms

from portal.capstone import models


class ApiForm(forms.ModelForm):
    class Meta:
        model = models.StudentApi
        fields = ["url"]


class ReportForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = ["file"]

portal/portal/hackathons/forms.py
import logging

from crispy_forms.layout import Field
from django import forms

from . import models

logger = logging.getLogger(__name__)


class CustomCheckbox(Field):
    template = "crispy/custom_checkbox.html"


class StudentAttendanceForm(forms.ModelForm):
    class Meta:
        model = models.Attendance
        fields = [
            # 'remote'
        ]

    def clean(self):
        cleaned_data = super().clean()
        if self.instance.hackathon.status != "taking_attendance":
            msg = "Marking attendance is closed"
            raise forms.ValidationError(msg)
        return cleaned_data


class TeamForm(forms.ModelForm):
    class Meta:
        model = models.Team
        fields = ["name", "logo"]


class SubmitForm(forms.Form):
    data = forms.FileField()

    class Meta:
        fields = ["data"]


class InstructorHackathonForm(forms.ModelForm):
    class Meta:
        model = models.Hackathon
        fields = [
            "status",
            "max_submissions",
            "team_size",
            "max_team_size",
            "max_teams",
            "descending",
            "script_file",
            "data_file",
        ]

    # def clean_teams_closed(self):
    #     if self.cleaned_data['teams_closed']:
    #         if not self.instance.teams.exists():
    #             # TODO: not shown
    #             raise forms.ValidationError("Generate teams first",
    #                                         code='invalid')
    #         self.cleaned_data['attendance_open'] = False

portal/portal/capstone/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from rest_framework.response import Response
from rest_framework.views import APIView

from portal.capstone import forms, models
from portal.users.models import User
from portal.users.views import InstructorMixin, StudentMixin

logger = logging.getLogger(__name__)


class StudentCapstoneListView(StudentMixin, ListView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/student/capstone_list.html"

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        self.object_list = self.get_queryset()
        data = []
        for capstone in self.object_list:
            api, _ = models.StudentApi.objects.get_or_create(
                capstone=capstone, user=request.user
            )
            data.append((capstone, api))

        context = self.get_context_data(object_list=data)
        return self.render_to_response(context)


class StudentCapstoneDetailView(StudentMixin, DetailView):
    model = models.Capstone
    template_name = "capstone/student/capstone_detail.html"

    # noinspection PyAttributeOutsideInit
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset=queryset)

        api, _ = models.StudentApi.objects.get_or_create(
            capstone=self.object,
            user=self.request.user,
        )

        reports = {}
        for type_choice in models.Report.Type.choices:
            report, _ = models.Report.objects.get_or_create(
                capstone=self.object,
                user=self.request.user,
                type=type_choice[0],
            )
            reports[type_choice[0]] = report

        return self.object, api, reports

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        capstone, api, reports = self.get_object()
        context = self.get_context_data(
            capstone=capstone,
            api=api,
            api_form=forms.ApiForm(instance=api),
            reports=[
                [report_type, forms.ReportForm(instance=report), report]
                for report_type, report in reports.items()
                if getattr(capstone, f"{report_type}_open")
            ],
        )
        return self.render_to_response(context)

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        capstone, api, reports = self.get_object()

        if "submit_api" in request.POST:
            form = forms.ApiForm(request.POST, instance=api)
            if form.is_valid():
                form.save()

        else:
            for report_type, report in reports.items():
                if f"submit_{report_type}" in request.POST:
                    form = forms.ReportForm(
                        request.POST, request.FILES, instance=report
                    )
                    if form.is_valid():
                        form.save()
                        messages.add_message(
                            request,
                            messages.SUCCESS,
                            "Report submited successfully!",
                        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("capstone:student-capstone-detail", args=(self.object.pk,))


class InstructorCapstoneListView(InstructorMixin, ListView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/instructor/capstone_list.html"


class InstructorCapstoneDetailView(InstructorMixin, DetailView):
    model = models.Capstone
    queryset = models.Capstone.objects.all()
    template_name = "capstone/instructor/capstone_detail.html"

    def get(
        self,
        request,
        *args,
        **kwargs,
    ):
        self.object = self.get_object()
        student_data = []
        for student in User.objects.filter(is_student=True):
            student_data.append(
                {
                    "user": student,
                    "api": models.StudentApi.objects.filter(
                        capstone=self.object,
                        user=student,
                    ).first(),
                    "proposal": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.proposal,
                    ).first(),
                    "report_provisory": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.report_provisory,
                    ).first(),
                    "report_final": models.Report.objects.filter(
                        capstone=self.object,
                        user=student,
                        type=models.Report.Type.report_final,
                    ).first(),
                },
            )

        context = self.get_context_data(
            object=self.object,
            students=student_data,
            workspace_url=settings.SLACK_WORKSPACE,
        )
        return self.render_to_response(context)


class CapstonePredictView(APIView):
    permission_classes = []

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        return Response({"proba": 0.6})


class CapstoneUpdateView(APIView):
    permission_classes = []

    def post(
        self,
        request,
        *args,
        **kwargs,
    ):
        return Response({"msg": "ok"})

portal/portal/templates/hackathons/instructor/hackathon_admin.html
{% extends "base.html" %}
{% load static %}
{% load grade_tags %}
{% load query_param_tags %}

{% block title %}{{ object.code }} Attendance{% endblock %}

{% block content %}
<div class="row mb-5 mt-5">
  <div class="col-md-auto">
    <h1>{{ object.code }}: {{ object.get_status_display }}</h1>
  </div>
  <div class="col-md-auto">
    <a href="{% url 'hackathons:instructor-hackathon-settings' hackathon.pk%}">
        <img src="{% static "open-iconic/svg/cog.svg" %}" alt="cog">
    </a>
  </div>
</div>

<!-- Actions -->
<div class="row">
    <h3>Actions</h3>
</div>
<div class="row">
  {% if object.status == "closed" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="marking_presences">
          <button type="submit"
                  class="btn btn-success">Mark student presences</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="closed">
          <button type="submit"
                  class="btn btn-success"
                  onclick="return confirm('This operation is unrecoverable!');"
          >Delete submissions</button>
        </form>
      </div>
    </div>
  {% elif object.status == "marking_presences" %}
    <div class="col-md-auto">
      <div class="mb-4">
          <button type="submit"
                  class="btn btn-success" form="theform">Presences Marked</button>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <a href="{% add_query_param 'filter_eligible' true %}" >
          <button type="submit" class="btn">Filter eligible</button>
        </a>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="closed">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% elif object.status == "generating_teams" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="ready">
          <button type="submit"
                  class="btn btn-success">Ready</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="generating_teams">
          <button type="submit"
                  class="btn btn-info"
                  onclick="return confirm('Are you sure you want to generate teams? THIS WILL ERASE THE PREVIOUSLY GENERATED TEAMS');"
          >Generate Teams</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="marking_presences">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back to marking presences?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% elif object.status == "ready" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="submissions_open">
          <button type="submit"
                  class="btn btn-success">Open for submissions</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="generating_teams">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back to generating teams?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% elif object.status == "submissions_open" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="submissions_closed">
          <button type="submit"
                  class="btn btn-success">Close submissions</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="ready">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back to before opening submissions?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% elif object.status == "submissions_closed" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="complete">
          <button type="submit"
                  class="btn btn-success">Finished</button>
        </form>
      </div>
    </div>
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="submissions_open">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back and re-open the submissions?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% elif object.status == "complete" %}
    <div class="col-md-auto">
      <div class="mb-4">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="status" value="submissions_closed">
          <button type="submit"
                  class="btn btn-danger"
                  onclick="return confirm('Are you sure you want to go back?');"
          >Go back</button>
        </form>
      </div>
    </div>
  {% endif %}
</div>

<!-- Student list -->
<div class="row mb-4">
  <form id="theform" method="POST">
    <input type="hidden" name="status" value="generating_teams">
    {% csrf_token %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Team</th>
          <th scope="col">Username</th>
          <th scope="col">Name</th>
{#          <th scope="col">Remote</th>#}
          <th scope="col">Present</th>
        </tr>
      </thead>
      <tbody>
       {% for item in object_list %}
        <tr>
          <td>{{ item.team.hackathon_team_id }}</td>
          <td>{{ item.student.username }}</td>
          <td>{{ item.student.name }}</td>
{#          <td>{{ item.attendance.remote }}</td>#}
          <td>
            {% if object.status == "marking_presences" %}
              <div class="form-check">
                <input type="checkbox"
                       class="form-check-input"
                       name="{{ item.student.username }}"
                       {% if item.attendance.present %}checked{% endif %}>
              </div>
              {% else %}
                {{ item.attendance.present }}
              {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
</div>
{% endblock content %}

portal/portal/templates/hackathons/instructor/hackathon_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ hackathon.code }}{% endblock %}

{% block content %}
  <div class="row mb-5 mt-5">
    <div class="col">
      <h1>{{ hackathon.code }}: {{ hackathon.get_status_display }}</h1>
    </div>
  </div>

    <!-- Submissions -->
    {% if hackathon.status in hackathon.can_submit_instructor %}
      <div class="row">
        <div class="col-md-auto">
          <div class="mb-4">
            <h3>Submit</h3>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ submit_form|crispy }}
              <button type="submit"
                      class="btn btn-success"
                      name="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    {% endif %}
{% endblock content %}

portal/portal/templates/hackathons/instructor/hackathon_list.html
{% extends "base.html" %}
{% load static %}
{% load grade_tags %}

{% block title %}Hackathons{% endblock %}

{% block content %}
<div class="row mb-5 mt-5">
  <div class="col">
    <h1>Hackathons</h1>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Code</th>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
      <th scope="col">Due Date</th>
      <th scope="col">Leaderboard</th>
      <th scope="col">Admin</th>
    </tr>
  </thead>
  <tbody>
   {% for obj in object_list %}
    <tr  id="row-{{ obj.code }}">
      <th>
        <a href="{% url 'hackathons:instructor-hackathon-detail' obj.pk %}">
          {{ obj.pk }}
        </a>
      </th>
      <td>{{ obj.name }}</td>
      <td>{{ obj.get_status_display }}</td>
      <td>{{ obj.due_date }}</td>
      <td>
        {% if obj.pk != 'HCKT06' %}
          <a href="{% url 'hackathons:leaderboard' obj.pk%}">
            Leaderboard
          </a>
        {% else %}
          <a href="{% url 'hackathons:frankenleaderboard'%}">
            Leaderboard
          </a>
        {% endif %}
      </td>
      <td>
        <a href="{% url 'hackathons:instructor-hackathon-admin' obj.pk %}">
          {{ obj.pk }}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

portal/portal/templates/hackathons/instructor/hackathon_settings.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ hackathon.code }}{% endblock %}

{% block content %}
<div class="row mb-5 mt-5">
  <div class="col">
    <h1>{{ hackathon.code }} Settings</h1>
  </div>
  <div class="col-md-auto">
    <a href="{% url 'hackathons:instructor-hackathon-detail' hackathon.pk%}">
      Attendance
    </a>
  </div>
  <div class="col-md-auto">
    <a href="{% url 'hackathons:leaderboard' hackathon.pk%}">
      Leaderboard
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-auto">
    <div class="mb-4">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock content %}

portal/portal/templates/hackathons/instructor/teams.html
{% extends "base.html" %}
{% load static %}
{% load grade_tags %}

{% block title %}Hackathons{% endblock %}

{% block content %}
<div class="container">
  <div class="row mb-5 mt-5">
    <div class="col">
      <h1>Hackathons</h1>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Submissions</th>
        <th scope="col">Remote</th>
        <th scope="col">Logo</th>
      </tr>
    </thead>
    <tbody>
     {% for obj in object_list %}
      <tr  id="row-{{ obj.code }}">
        <th>{{ obj.hackthon_team_id }}</th>
        <td>{{ obj.name }}</td>
        <td>{{ obj.submissions }}</td>
        <td>{{ obj.remote }}</td>
        <td><img src="{{ obj.logo }}" alt="Logo"></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}